### ISSUE TITLE
Issue when running Anova example

### ISSUE THREAD

**Issue by MManiglia** [klabhub/bayesFactor#2]
When I try to run the following examples:

modelFull = fitlme(data,'rt~ori*freq');
bfFull = bf.anova(data,'rt~ori*freq');
bfFull
anova(modelFull)

I get this error

Undefined function or variable 'contGMatrix'.

Error in bf.internal.rouderS

Error in bf.internal.nWayAnova>@(g)(bf.internal.rouderS(g,y,X,sharedPriors,p.Results.continuousIx,p.Results.options)) (line
43)
    thisRouderS = @(g)(bf.internal.rouderS(g,y,X,sharedPriors,p.Results.continuousIx,p.Results.options));

Error in bf.internal.mcIntegral (line 26)
bf10Samples = fun(g);

Error in bf.internal.nWayAnova (line 44)
    bf10 = bf.internal.mcIntegral(thisRouderS,p.Results.scalePerSharedPrior,p.Results.options);

Error in bf.anova (line 220)
bf10 =
bf.internal.nWayAnova(y,X,'sharedPriors',fullSharedPriorIx,'options',p.Results.options,'scale',fullScale,'continuous',contIx);

**Comment by bartkrekelberg** [comment]
Which version of Matlab are you running?

**Comment by bartkrekelberg** [comment]
Thanks for the bug report. This is solved in the current HEAD (Because it could be used in the parfor, the contGMatrix has to be defined even if it is never used).
