### ISSUE TITLE
the same bug as MManiglia when running Anova example (rouderFigure5)

### ISSUE THREAD

**Issue by xhhe0731** [klabhub/bayesFactor#3]
**Describe the bug**
error in rouderFigure5

**To Reproduce**
run the example rouderFigure5

** Versions:**
 - Matlab version: R2020b (the same bug also occurs in R2019a)

**Screenshots**
<img width="666" alt="14b622cc45545d434be86aacd66db59" src="https://user-images.githubusercontent.com/94375765/141796111-ceecbfe2-1968-4ede-81f5-f8f31b1b22c5.png">

**Comment by bartkrekelberg** [comment]
Thanks for the bug report. This is solved in the current HEAD (Becuase it could be used in the parfor, the contGMatrix has to be defined even if it is never used).
