### ISSUE TITLE
Bug with bf.ttest2 ?

### ISSUE THREAD

**Issue by fabien-vinckier** [klabhub/bayesFactor#4]
Dear Bart,

I probably misunderstood something but I have some issues to use bf.ttest2...

When I use bf.ttest2, I get the following error: 

bf.ttest2(randn(36, 1), randn(22, 1))

>Error using bf.ttest (line 58)
>'stats' is not a recognized parameter. For a list of valid name-value pair arguments, see the documentation for this function.
>Error in bf.ttest2 (line 61)
>bf10 = bf.ttest('stats',statsForBf); 

My matlab is quite old but I get the same error with a 2021 version... 

I apologize in advance if I misunderstood how to use the function.

With many thanks and my very best wishes,

Fabien

**Comment by bartkrekelberg** [comment]
Hi Fabien
You're right this was a bug. I had changed the ttest code, but did not adjust the ttest2 code and documentation yet. 

I have changed both now to force users to specify either the samples themselves (X and Y vectors for ttest2)  OR
the T and the N per sample. See help bf.ttest2 for more explanation. 

With this you should be able to compute BFs for every reported t-test.

Bart

**Comment by fabien-vinckier** [comment]
It works perfectly well now, thanks a lot !
